### PR TITLE
Catch the "Close normal" error

### LINKED ISSUE #44: Unexpected error received from Poseidon
In Sentry, I noticed some reoccurring issues with errors received from Poseidon and tried to debug them. Below is an example that occurred today. It shows that the messages were received correctly and (from my expectation) are complete. However, instead of terminating the execution normally, Poseidon sends an error to CodeOcean.

Is there something we can improve here to avoid the error? Logs are attached for CodeOcean and Poseidon. As the connection to Nomad was closed normally, there might be some race condition?

CodeOcean:

```
D, [2021-11-18T14:57:09.389856 #3606] DEBUG -- : 2021-11-18 14:57:09.389779572 UTC: Receiving from wss://poseidon.codeocean.xopic.de:7200/api/v1/runners/29-98c10ec0-487f-11ec-b035-fa163e05d94e/websocket?executionID=26da8d47-b887-480a-aa09-31cfe79c23f7: "{\"type\":\"stdout\",\"data\":\"************* Module aufgabe123\\r\\n aufgabe123.py:1: convention (C0326, bad-whitespace, ) Exactly one space required after comma\\r\\n print(\\\"Viel\\\",\\\"Spaß\\\",\\\"im\\\",\\\"Sommercamp\\\")\\r\\n             ^\\r\\n aufgabe123.py:1: convention (C0326, bad-whitespace, ) Exactly one space required after comma\\r\\n print(\\\"Viel\\\",\\\"Spaß\\\",\\\"im\\\",\\\"Sommercamp\\\")\\r\\n                    ^\\r\\n aufgabe123.py:1: convention (C0326, bad-whitespace, ) Exactly one space required after comma\\r\\n print(\\\"Viel\\\",\\\"Spaß\\\",\\\"im\\\",\\\"Sommercamp\\\")\\r\\n                         ^\\r\\n \\r\\n\"}"
D, [2021-11-18T14:57:09.390751 #3606] DEBUG -- : 2021-11-18 14:57:09.390718572 UTC: Receiving from wss://poseidon.codeocean.xopic.de:7200/api/v1/runners/29-98c10ec0-487f-11ec-b035-fa163e05d94e/websocket?executionID=26da8d47-b887-480a-aa09-31cfe79c23f7: "{\"type\":\"stdout\",\"data\":\" -------------------------------------\\r\\n Your code has been rated at -20.00/10\\r\\n \\r\\n\"}"
D, [2021-11-18T14:57:09.487876 #3606] DEBUG -- : 2021-11-18 14:57:09.487818009 UTC: Receiving from wss://poseidon.codeocean.xopic.de:7200/api/v1/runners/29-98c10ec0-487f-11ec-b035-fa163e05d94e/websocket?executionID=26da8d47-b887-480a-aa09-31cfe79c23f7: "{\"type\":\"stdout\",\"data\":\" \"}"
D, [2021-11-18T14:57:09.565863 #3606] DEBUG -- : 2021-11-18 14:57:09.565802873 UTC: Receiving from wss://poseidon.codeocean.xopic.de:7200/api/v1/runners/29-98c10ec0-487f-11ec-b035-fa163e05d94e/websocket?executionID=26da8d47-b887-480a-aa09-31cfe79c23f7: "{\"type\":\"error\",\"data\":\"Error executing the request\"}"
D, [2021-11-18T14:57:09.574277 #3606] DEBUG -- : 2021-11-18 14:57:09.574243386 UTC: Closing connection to wss://poseidon.codeocean.xopic.de:7200/api/v1/runners/29-98c10ec0-487f-11ec-b035-fa163e05d94e/websocket?executionID=26da8d47-b887-480a-aa09-31cfe79c23f7 with status: established
D, [2021-11-18T14:57:09.574560 #3606] DEBUG -- : 2021-11-18 14:57:09.574531158 UTC: Destroying runner at https://poseidon.codeocean.xopic.de:7200/api/v1/runners/29-98c10ec0-487f-11ec-b035-fa163e05d94e
I, [2021-11-18T14:57:09.577494 #3606]  INFO -- sentry: Sending envelope [event] ed27e79b516b4f7a9a85ed8c50b0bfe5 to Sentry
D, [2021-11-18T14:57:09.671942 #3606] DEBUG -- : 2021-11-18 14:57:09.671907515 UTC: Finished destroying runner
D, [2021-11-18T14:57:09.672245 #3606] DEBUG -- : 2021-11-18 14:57:09.672217529 UTC: Closed connection to wss://poseidon.codeocean.xopic.de:7200/api/v1/runners/29-98c10ec0-487f-11ec-b035-fa163e05d94e/websocket?executionID=26da8d47-b887-480a-aa09-31cfe79c23f7 with status: established
D, [2021-11-18T14:57:09.673207 #3606] DEBUG -- : Running command `python3 -B -m unittest --verbose test_style` failed: Execution terminated with an unknown reason
```

Poseidon:
```
Nov 18 14:57:07 poseidon poseidon[3701]: time="2021-11-18T14:57:07.820827Z" level=debug code=204 duration=198.124233ms method=PATCH path=/api/v1/runners/29-98c10ec0-487f-11ec-b035-fa163e05d94e/files user_agent="Faraday v1.8.0"
Nov 18 14:57:07 poseidon poseidon[3701]: time="2021-11-18T14:57:07.825622Z" level=debug code=200 duration="116.768µs" method=POST path=/api/v1/runners/29-98c10ec0-487f-11ec-b035-fa163e05d94e/execute user_agent="Faraday v1.8.0"
Nov 18 14:57:07 poseidon poseidon[3701]: time="2021-11-18T14:57:07.846700Z" level=info msg="Running execution" executionID=635e39df-7b68-4ad5-9699-b535a88481d4 package=api runnerId=29-98c10ec0-487f-11ec-b035-fa163e05d94e
Nov 18 14:57:08 poseidon poseidon[3701]: time="2021-11-18T14:57:08.301369Z" level=info msg="Execution returned" package=api
Nov 18 14:57:08 poseidon poseidon[3701]: time="2021-11-18T14:57:08.301470Z" level=debug exit_code=0 package=api
Nov 18 14:57:08 poseidon poseidon[3701]: time="2021-11-18T14:57:08.301640Z" level=debug code=200 duration=455.044313ms method=GET path=/api/v1/runners/29-98c10ec0-487f-11ec-b035-fa163e05d94e/websocket user_agent=
Nov 18 14:57:08 poseidon poseidon[3701]: time="2021-11-18T14:57:08.331060Z" level=debug code=200 duration="160.3µs" method=POST path=/api/v1/runners/29-98c10ec0-487f-11ec-b035-fa163e05d94e/execute user_agent="Faraday v1.8.0"
Nov 18 14:57:08 poseidon poseidon[3701]: time="2021-11-18T14:57:08.356571Z" level=info msg="Running execution" executionID=26da8d47-b887-480a-aa09-31cfe79c23f7 package=api runnerId=29-98c10ec0-487f-11ec-b035-fa163e05d94e
Nov 18 14:57:08 poseidon poseidon[3701]: time="2021-11-18T14:57:08.795301Z" level=info msg="Execution returned" package=api
Nov 18 14:57:08 poseidon poseidon[3701]: time="2021-11-18T14:57:08.795490Z" level=debug exit_code=0 package=api
Nov 18 14:57:08 poseidon poseidon[3701]: time="2021-11-18T14:57:08.795691Z" level=debug code=200 duration=1.208351517s method=GET path=/api/v1/runners/10-aa4e11de-487e-11ec-b035-fa163e05d94e/websocket user_agent=
Nov 18 14:57:09 poseidon poseidon[3701]: time="2021-11-18T14:57:09.565419Z" level=info msg="Execution returned" package=api
Nov 18 14:57:09 poseidon poseidon[3701]: time="2021-11-18T14:57:09.565612Z" level=warning msg="Error executing the request" error="error executing command in allocation: websocket closed before receiving exit code: websocket: close 1000 (normal)" package=api
Nov 18 14:57:09 poseidon poseidon[3701]: time="2021-11-18T14:57:09.565781Z" level=debug code=200 duration=1.209390714s method=GET path=/api/v1/runners/29-98c10ec0-487f-11ec-b035-fa163e05d94e/websocket user_agent=
Nov 18 14:57:09 poseidon poseidon[3701]: time="2021-11-18T14:57:09.671487Z" level=debug code=204 duration=94.27816ms method=DELETE path=/api/v1/runners/29-98c10ec0-487f-11ec-b035-fa163e05d94e user_agent="Faraday v1.8.0"
Nov 18 14:57:09 poseidon poseidon[3701]: time="2021-11-18T14:57:09.888922Z" level=debug msg="Runner stopped" id=29-98c10ec0-487f-11ec-b035-fa163e05d94e package=runner
```

### PR DESCRIPTION
**Pull request by mpass99**
Closes #44

### CODE REVIEW

**Comment by mpass99** [comment]
The exit code could not be received. Should we set another value as exit code?

**Comment by MrSerth** [comment]
I remember that we had the exit code discussion previously (as DCP is not capable of retrieving the exit code as well). In that case, we always assumed normal termination (code 0). I would expect that this exit code 0 is suitable in most occurrences of this error (or do you have other information?). So, for the first implementation, I would catch the error, assume normal termination (code 0) and be fine with that.

A possible improvement (that would require a small refactoring in CodeOcean / the API) would be to handle the exit code as an optional attribute and don't show anything to the user if it is missing.

**Review by MrSerth — COMMENTED** [review]
Thanks for the change and implementation of returning a successful exit code. I assume that we won't send anything to Sentry in this case, right? (My assumption: Because the Sentry hook is not registered for [info events](https://github.com/openhpi/poseidon/blob/3ae83217d772fe6512cca4df7e7e5a560d354c0c/pkg/logging/sentry_hook.go#L30-L38))

**Comment by mpass99** [comment]
> I assume that we won't send anything to Sentry in this case, right?

**Comment by MrSerth** [comment]
> > I assume that we won't send anything to Sentry in this case, right?
> 
> Yes, based on a normal termination, I would not have sent anything to Sentry; although it would be exciting to see how often this occurs. Should we rather log it at "warning" level?

I see the interest but would rather not do it (at least not via Sentry). For one, Sentry is more dedicated to error tracing, and (therefore) the pricing model is based on each event. As a consequence, "counting" via Sentry might get expensive and as a project, we have an overall error limit per month (for all projects). Do you have another idea to log / count?

**Comment by mpass99** [comment]
> Do you have another idea to log / count?

We already have a "statistics" route. We could create a statistics controller and count things like "How often is which route requested" or "How often is the error code missing". With such a controller we could also provide an prometheus endpoint.
However, as this is a bit of work for currently not that much added value, I would assign it a low priority.

**Comment by MrSerth** [comment]
> We already have a "statistics" route. We could create a statistics controller and count things like "How often is which route requested" or "How often is the error code missing". With such a controller we could also provide an prometheus endpoint.

I agree. Let's move this discussion into a dedicated issue and add it with a low priority. For these, we might also need to check for persistence/server restarts (depending on the concrete implementation).

**Pull request merged**
