### PR TITLE
Add automatic detection for release version

### PR DESCRIPTION
**Pull request by MrSerth**
During the latest deployment, I noticed that we might run into issues with identifying the release information. Therefore, I changed the process to automatically grab the git hash used to build the binary. We can still specify a manual release version, e.g., to be used during development.

### CODE REVIEW

**Review by mpass99 — APPROVED** [review]
I remember when I saw this first reading the Go 1.18 Release Notes. Cool to have it in Poseidon :star_struck: 

We could think about adding behavior for the ` vcs.modified=true` setting :man_shrugging:

**Comment by MrSerth** [comment]
> We could think about adding behavior for the  vcs.modified=true setting 🤷‍♂️

I also thought about this. Potentially, we could just append "-modified", as we've done before. However, as we currently build during our GitLab CI pipeline, we rarely have those "modified" builds.

**Comment by mpass99** [comment]
I agree - not really important. But if we spot the prepended "modified", we might discover a new error..

**Comment by MrSerth** [comment]
> I agree - not really important. But if we spot the prepended "modified", we might discover a new error..

Indeed. I changed the code accordingly.

**Review by mpass99 — APPROVED** [review]

**Pull request merged**
